### ISSUE TITLE
Missing requirements and really slow

### ISSUE THREAD

**Issue by Seluj78** [MysteryCoder456/Python.io#5]
Hey dude ! Amazing work !

You just forgot to add a `requirements.txt` file with "pygame" in it and add the step to tell people to install it.

Also it runs really slowly on my Macbook pro 2018. I upped the fps and it is slightly faster but still 
https://streamable.com/6mx9e

**Comment by MysteryCoder456** [comment]
Thanks a lot Seluj78! I’m sorry I forgot to add to Pygame to the requirements, because I was kinda in a rush when I was making them. I’ll add them as soon as I can. Btw I used to have the same issues of pygame running slower than usual. On my MacBook Pro 2017 it works fine at 60fps with [this fix](https://stackoverflow.com/questions/31685936/pygame-application-runs-slower-on-mac-than-on-pc). Hope this helps.

**Comment by Seluj78** [comment]
In that case you should add the fix to the readme

**Comment by MysteryCoder456** [comment]
Already did. It’s in the how to install section.
